# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
A = np.arange(0,10)
B = np.reshape(A,(2,5))
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])
c = np.vstack([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
e = np.ones([2,5])
f = np.hstack([d,e])
f

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [18]:
g = d.flatten()
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [20]:
h = np.vstack([d,[10,11,12,13,14]])
i = h.flatten()
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [22]:
j = i.reshape(5,3)
j

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [30]:
k = np.full((5,5), 5)
l = np.square([k])
l

array([[[25, 25, 25, 25, 25],
        [25, 25, 25, 25, 25],
        [25, 25, 25, 25, 25],
        [25, 25, 25, 25, 25],
        [25, 25, 25, 25, 25]]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [32]:
m = np.full((5,6), 8)
n = np.mean([m])
n

8.0

## Question:9

### Find the standard deviation of the previous array in Q8?

In [33]:
o = np.std([m])
o

0.0

## Question:10

### Find the median of the previous array in Q8?

In [34]:
p = np.median([m])
p

8.0

## Question:11

### Find the transpose of the previous array in Q8?

In [35]:
q = np.transpose([m])
q

array([[[8],
        [8],
        [8],
        [8],
        [8]],

       [[8],
        [8],
        [8],
        [8],
        [8]],

       [[8],
        [8],
        [8],
        [8],
        [8]],

       [[8],
        [8],
        [8],
        [8],
        [8]],

       [[8],
        [8],
        [8],
        [8],
        [8]],

       [[8],
        [8],
        [8],
        [8],
        [8]]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [36]:
r = np.full((4,4), 4)
s = np.trace(r)
s

16

## Question:13

### Find the determinant of the previous array in Q12?

In [38]:
t = np.linalg.det(r)
t

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [40]:
u = np.percentile(d,5)
print(u)
v = np.percentile(d,95)
v

0.45


8.549999999999999

## Question:15

### How to find if a given array has any null values?

In [49]:
w = np.array([[1,2,3,4,5,6],[0,4,57,0,2,0]])
w

array([[ 1,  2,  3,  4,  5,  6],
       [ 0,  4, 57,  0,  2,  0]])

In [57]:
w > 0


array([[ True,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True, False]])

In [56]:
w[w==0]

array([0, 0, 0])